import { defineSchema } from "convex/server";
import { tables } from "./generatedSchema";

/**
 * Final schema for the local Better Auth component.
 *
 * The raw tables are auto-generated by `npx auth generate --output generatedSchema.ts`.
 * We re-import them here so we can add custom indexes that survive regeneration.
 *
 * To regenerate the source tables (safe to run repeatedly):
 *   cd convex/betterAuth
 *   npx auth generate --output generatedSchema.ts
 *
 * Note: this schema is scoped to the sub-component. App-level tables live
 * in `../schema.ts` and are NOT included here.
 */
const schema = defineSchema({
  ...tables,
  // Custom indexes survive regeneration of `generatedSchema.ts`.
  //
  // The passkey plugin looks up passkeys by `credentialID` (the WebAuthn
  // credential id, base64url-encoded). Without an index that begins with
  // `credentialID`, the adapter falls back to `db.get(id)` and crashes with
  // `Invalid argument 'id' for 'db.get': Unable to decode ID: Invalid ID
  // length 29` (the credentialID is a 29-char string, not a Convex _id).
  passkey: tables.passkey.index("credentialID", ["credentialID"]),
});

export default schema;
